apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: consumer
  name: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - image: docker.io/lemberski/consumer:latest
          name: consumer
          imagePullPolicy: Always
          ports:
            - containerPort: 8080