server:
  port: 8080
  shutdown: graceful

spring:
  kafka:
    bootstrap-servers: my-cluster-kafka-bootstrap:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  lifecycle:
    timeout-per-shutdown-phase: 20s

management:
  endpoint:
    health:
      probes:
        enabled: true